version: '3'

services:
  station:
    image: therhenals/thradio_stations
    build: .
    ports:
      - 9001:9001
      - 8000:8000
      - 8010:8010
    volumes:
      - stations_data:/var/thradio/stations

volumes:
  stations_data:
    name: thradio_stations_data
